[package]
name = "sp800-185"
version = "0.1.0"
authors = ["quininer kel <quininer@live.com>"]

[dependencies]
tiny-keccak = { git = "https://github.com/quininer/tiny-keccak" }
byteorder = "*"
rayon = { version = "*", optional = true }

[features]
parallelhash = [ "rayon" ]
